/* Generated by Frama-C */
int encode(int xin1, int xin2);

int filtez(int *bpl, int *dlt_0);

void upzero(int dlt_0, int *dlti, int *bli);

int filtep(int rlt1_0, int al1_0, int rlt2_0, int al2_0);

int quantl(int el_0, int detl_0);

int invqxl(int il_0, int detl_0, int *code_table, int mode);

int logscl(int il_0, int nbl_0);

int scalel(int nbl_0, int shift_constant);

int uppol2(int al1_0, int al2_0, int plt_0, int plt1_0, int plt2_0);

int uppol1(int al1_0, int apl2, int plt_0, int plt1_0);

int invqah(int ih_0, int deth_0);

int logsch(int ih_0, int nbh_0);

int tqmf[24];
int h[24] =
  {12,
   -44,
   -44,
   212,
   48,
   -624,
   128,
   1448,
   -840,
   -3220,
   3804,
   15504,
   15504,
   3804,
   -3220,
   -840,
   1448,
   128,
   -624,
   48,
   212,
   -44,
   -44,
   12};
int xl;
int xh;
int accumc[11];
int accumd[11];
int xout1;
int xout2;
int xs;
int xd;
int il;
int szl;
int spl;
int sl;
int el;
int qq4_code4_table[16] =
  {0,
   -20456,
   -12896,
   -8968,
   -6288,
   -4240,
   -2584,
   -1200,
   20456,
   12896,
   8968,
   6288,
   4240,
   2584,
   1200,
   0};
int qq5_code5_table[32] =
  {-280,
   -280,
   -23352,
   -17560,
   -14120,
   -11664,
   -9752,
   -8184,
   -6864,
   -5712,
   -4696,
   -3784,
   -2960,
   -2208,
   -1520,
   -880,
   23352,
   17560,
   14120,
   11664,
   9752,
   8184,
   6864,
   5712,
   4696,
   3784,
   2960,
   2208,
   1520,
   880,
   280,
   -280};
int qq6_code6_table[64] =
  {-136,
   -136,
   -136,
   -136,
   -24808,
   -21904,
   -19008,
   -16704,
   -14984,
   -13512,
   -12280,
   -11192,
   -10232,
   -9360,
   -8576,
   -7856,
   -7192,
   -6576,
   -6000,
   -5456,
   -4944,
   -4464,
   -4008,
   -3576,
   -3168,
   -2776,
   -2400,
   -2032,
   -1688,
   -1360,
   -1040,
   -728,
   24808,
   21904,
   19008,
   16704,
   14984,
   13512,
   12280,
   11192,
   10232,
   9360,
   8576,
   7856,
   7192,
   6576,
   6000,
   5456,
   4944,
   4464,
   4008,
   3576,
   3168,
   2776,
   2400,
   2032,
   1688,
   1360,
   1040,
   728,
   432,
   136,
   -432,
   -136};
int delay_bpl[6];
int delay_dltx[6];
int wl_code_table[16] =
  {-60,
   3042,
   1198,
   538,
   334,
   172,
   58,
   -30,
   3042,
   1198,
   538,
   334,
   172,
   58,
   -30,
   -60};
int wl_table[8] = {-60, -30, 58, 172, 334, 538, 1198, 3042};
int ilb_table[32] =
  {2048,
   2093,
   2139,
   2186,
   2233,
   2282,
   2332,
   2383,
   2435,
   2489,
   2543,
   2599,
   2656,
   2714,
   2774,
   2834,
   2896,
   2960,
   3025,
   3091,
   3158,
   3228,
   3298,
   3371,
   3444,
   3520,
   3597,
   3676,
   3756,
   3838,
   3922,
   4008};
int nbl;
int al1;
int al2;
int plt;
int plt1;
int plt2;
int rs;
int dlt;
int rlt;
int rlt1;
int rlt2;
int decis_levl[30] =
  {280,
   576,
   880,
   1200,
   1520,
   1864,
   2208,
   2584,
   2960,
   3376,
   3784,
   4240,
   4696,
   5200,
   5712,
   6288,
   6864,
   7520,
   8184,
   8968,
   9752,
   10712,
   11664,
   12896,
   14120,
   15840,
   17560,
   20456,
   23352,
   32767};
int detl;
int quant26bt_pos[31] =
  {61,
   60,
   59,
   58,
   57,
   56,
   55,
   54,
   53,
   52,
   51,
   50,
   49,
   48,
   47,
   46,
   45,
   44,
   43,
   42,
   41,
   40,
   39,
   38,
   37,
   36,
   35,
   34,
   33,
   32,
   32};
int quant26bt_neg[31] =
  {63,
   62,
   31,
   30,
   29,
   28,
   27,
   26,
   25,
   24,
   23,
   22,
   21,
   20,
   19,
   18,
   17,
   16,
   15,
   14,
   13,
   12,
   11,
   10,
   9,
   8,
   7,
   6,
   5,
   4,
   4};
int deth;
int sh;
int eh;
int qq2_code2_table[4] = {-7408, -1616, 7408, 1616};
int wh_code_table[4] = {798, -214, 798, -214};
int dh;
int ih;
int nbh;
int szh;
int sph;
int ph;
int yh;
int rh;
int delay_dhx[6];
int delay_bph[6];
int ah1;
int ah2;
int ph1;
int ph2;
int rh1;
int rh2;
int ilr;
int yl;
int rl;
int dec_deth;
int dec_detl;
int dec_dlt;
int dec_del_bpl[6];
int dec_del_dltx[6];
int dec_plt;
int dec_plt1;
int dec_plt2;
int dec_szl;
int dec_spl;
int dec_sl;
int dec_rlt1;
int dec_rlt2;
int dec_rlt;
int dec_al1;
int dec_al2;
int dl;
int dec_nbl;
int dec_yh;
int dec_dh;
int dec_nbh;
int dec_del_bph[6];
int dec_del_dhx[6];
int dec_szh;
int dec_rh1;
int dec_rh2;
int dec_ah1;
int dec_ah2;
int dec_ph;
int dec_sph;
int dec_sh;
int dec_rh;
int dec_ph1;
int dec_ph2;
int abs(int x)
{
  int m;
  if (x >= 0) m = x; else m = - x;
  return m;
}

/*@ ensures sh ≡ 0 ∨ sh ≡ -2; */
int encode(int xin1, int xin2)
{
  int __retres;
  int i;
  int *h_ptr;
  int *tqmf_ptr;
  int *tqmf_ptr1;
  long xa;
  long xb;
  int decis;
  int *tmp;
  int *tmp_0;
  int *tmp_1;
  int *tmp_2;
  int *tmp_7;
  int *tmp_8;
  int *tmp_9;
  int *tmp_12;
  int tmp_13;
  h_ptr = h;
  tqmf_ptr = tqmf;
  { /* sequence */
    tmp = tqmf_ptr;
    tqmf_ptr ++;
    tmp_0 = h_ptr;
    h_ptr ++;
    xa = (long)*tmp * (long)*tmp_0;
  }
  { /* sequence */
    tmp_1 = tqmf_ptr;
    tqmf_ptr ++;
    tmp_2 = h_ptr;
    h_ptr ++;
    xb = (long)*tmp_1 * (long)*tmp_2;
  }
  i = 0;
  while (i < 10) {
    {
      int *tmp_3;
      int *tmp_4;
      int *tmp_5;
      int *tmp_6;
      { /* sequence */
        tmp_3 = tqmf_ptr;
        tqmf_ptr ++;
        tmp_4 = h_ptr;
        h_ptr ++;
        xa += (long)*tmp_3 * (long)*tmp_4;
      }
      { /* sequence */
        tmp_5 = tqmf_ptr;
        tqmf_ptr ++;
        tmp_6 = h_ptr;
        h_ptr ++;
        xb += (long)*tmp_5 * (long)*tmp_6;
      }
    }
    i ++;
  }
  { /* sequence */
    tmp_7 = tqmf_ptr;
    tqmf_ptr ++;
    tmp_8 = h_ptr;
    h_ptr ++;
    xa += (long)*tmp_7 * (long)*tmp_8;
  }
  { /* sequence */
    tmp_9 = h_ptr;
    h_ptr ++;
    xb += (long)*tqmf_ptr * (long)*tmp_9;
  }
  tqmf_ptr1 = tqmf_ptr - 2;
  i = 0;
  while (i < 22) {
    int *tmp_10;
    int *tmp_11;
    { /* sequence */
      tmp_10 = tqmf_ptr;
      tqmf_ptr --;
      tmp_11 = tqmf_ptr1;
      tqmf_ptr1 --;
      *tmp_10 = *tmp_11;
    }
    i ++;
  }
  { /* sequence */
    tmp_12 = tqmf_ptr;
    tqmf_ptr --;
    *tmp_12 = xin1;
  }
  *tqmf_ptr = xin2;
  xl = (int)((xa + xb) >> 15);
  xh = (int)((xa - xb) >> 15);
  szl = filtez(delay_bpl,delay_dltx);
  spl = filtep(rlt1,al1,rlt2,al2);
  sl = szl + spl;
  el = xl - sl;
  il = quantl(el,detl);
  dlt = (int)((long)detl * (long)qq4_code4_table[il >> 2] >> 15);
  nbl = logscl(il,nbl);
  detl = scalel(nbl,8);
  plt = dlt + szl;
  upzero(dlt,delay_dltx,delay_bpl);
  al2 = uppol2(al1,al2,plt,plt1,plt2);
  al1 = uppol1(al1,al2,plt,plt1);
  rlt = sl + dlt;
  rlt2 = rlt1;
  rlt1 = rlt;
  plt2 = plt1;
  plt1 = plt;
  szh = filtez(delay_bph,delay_dhx);
  sph = filtep(rh1,ah1,rh2,ah2);
  sh = sph + szh;
  eh = xh - sh;
  if (eh >= 0) ih = 3; else ih = 1;
  decis = (int)(564L * (long)deth >> 12L);
  { /* sequence */
    tmp_13 = abs(eh);
    ;
  }
  if (tmp_13 > decis) ih --;
  dh = (int)((long)deth * (long)qq2_code2_table[ih] >> 15L);
  nbh = logsch(ih,nbh);
  deth = scalel(nbh,10);
  ph = dh + szh;
  upzero(dh,delay_dhx,delay_bph);
  ah2 = uppol2(ah1,ah2,ph,ph1,ph2);
  ah1 = uppol1(ah1,ah2,ph,ph1);
  yh = sh + dh;
  rh2 = rh1;
  rh1 = yh;
  ph2 = ph1;
  ph1 = ph;
  __retres = il | (ih << 6);
  return __retres;
}

int filtez(int *bpl, int *dlt_0)
{
  int __retres;
  int i;
  long zl;
  int *tmp;
  int *tmp_0;
  { /* sequence */
    tmp = bpl;
    bpl ++;
    tmp_0 = dlt_0;
    dlt_0 ++;
    zl = (long)*tmp * (long)*tmp_0;
  }
  i = 1;
  while (i < 6) {
    int *tmp_1;
    int *tmp_2;
    { /* sequence */
      tmp_1 = bpl;
      bpl ++;
      tmp_2 = dlt_0;
      dlt_0 ++;
      zl += (long)*tmp_1 * (long)*tmp_2;
    }
    i ++;
  }
  __retres = (int)(zl >> 14);
  return __retres;
}

int filtep(int rlt1_0, int al1_0, int rlt2_0, int al2_0)
{
  int __retres;
  long pl;
  long pl2;
  pl = (long)(2 * rlt1_0);
  pl = (long)al1_0 * pl;
  pl2 = (long)(2 * rlt2_0);
  pl += (long)al2_0 * pl2;
  __retres = (int)(pl >> 15);
  return __retres;
}

int quantl(int el_0, int detl_0)
{
  int ril;
  int mil;
  long wd;
  long decis;
  wd = (long)abs(el_0);
  mil = 0;
  decis = (long)decis_levl[mil] * (long)detl_0 >> 15L;
  while (1) {
    if (wd <= decis) {
      if (! (mil < 29)) break;
    }
    else break;
    mil ++;
    decis = (long)decis_levl[mil] * (long)detl_0 >> 15L;
  }
  if (el_0 >= 0) ril = quant26bt_pos[mil]; else ril = quant26bt_neg[mil];
  return ril;
}

int invqxl(int il_0, int detl_0, int *code_table, int mode)
{
  int __retres;
  long dlt_0;
  dlt_0 = (long)detl_0 * (long)*(code_table + (il_0 >> (mode - 1)));
  __retres = (int)(dlt_0 >> 15);
  return __retres;
}

int logscl(int il_0, int nbl_0)
{
  long wd;
  wd = (long)nbl_0 * 127L >> 7L;
  nbl_0 = (int)wd + wl_code_table[il_0 >> 2];
  if (nbl_0 < 0) nbl_0 = 0;
  if (nbl_0 > 18432) nbl_0 = 18432;
  return nbl_0;
}

int scalel(int nbl_0, int shift_constant)
{
  int __retres;
  int wd1;
  int wd2;
  int wd3;
  wd1 = (nbl_0 >> 6) & 31;
  wd2 = nbl_0 >> 11;
  wd3 = ilb_table[wd1] >> ((shift_constant + 1) - wd2);
  __retres = wd3 << 3;
  return __retres;
}

void upzero(int dlt_0, int *dlti, int *bli)
{
  int i;
  int wd2;
  int wd3;
  if (dlt_0 == 0) {
    i = 0;
    while (i < 6) {
      *(bli + i) = (int)(255L * (long)*(bli + i) >> 8L);
      i ++;
    }
  }
  else {
    i = 0;
    while (i < 6) {
      if ((long)dlt_0 * (long)*(dlti + i) >= (long)0) wd2 = 128;
      else wd2 = -128;
      wd3 = (int)(255L * (long)*(bli + i) >> 8L);
      *(bli + i) = wd2 + wd3;
      i ++;
    }
  }
  *(dlti + 5) = *(dlti + 4);
  *(dlti + 4) = *(dlti + 3);
  *(dlti + 3) = *(dlti + 2);
  *(dlti + 1) = *(dlti + 0);
  *(dlti + 0) = dlt_0;
  return;
}

int uppol2(int al1_0, int al2_0, int plt_0, int plt1_0, int plt2_0)
{
  long wd2;
  long wd4;
  int apl2;
  wd2 = 4L * (long)al1_0;
  if ((long)plt_0 * (long)plt1_0 >= 0L) wd2 = - wd2;
  wd2 >>= 7;
  if ((long)plt_0 * (long)plt2_0 >= 0L) wd4 = wd2 + (long)128;
  else wd4 = wd2 - (long)128;
  apl2 = (int)(wd4 + (127L * (long)al2_0 >> 7L));
  if (apl2 > 12288) apl2 = 12288;
  if (apl2 < -12288) apl2 = -12288;
  return apl2;
}

int uppol1(int al1_0, int apl2, int plt_0, int plt1_0)
{
  long wd2;
  int wd3;
  int apl1;
  wd2 = (long)al1_0 * 255L >> 8L;
  if ((long)plt_0 * (long)plt1_0 >= 0L) apl1 = (int)wd2 + 192;
  else apl1 = (int)wd2 - 192;
  wd3 = 15360 - apl2;
  if (apl1 > wd3) apl1 = wd3;
  if (apl1 < - wd3) apl1 = - wd3;
  return apl1;
}

int invqah(int ih_0, int deth_0)
{
  int __retres;
  long rdh;
  rdh = (long)deth_0 * (long)qq2_code2_table[ih_0] >> 15L;
  __retres = (int)rdh;
  return __retres;
}

int logsch(int ih_0, int nbh_0)
{
  int wd;
  wd = (int)((long)nbh_0 * 127L >> 7L);
  nbh_0 = wd + wh_code_table[ih_0];
  if (nbh_0 < 0) nbh_0 = 0;
  if (nbh_0 > 22528) nbh_0 = 22528;
  return nbh_0;
}

int test_data[10] = {1, 0, 1, 0, 1, 1, 1, 1, 1, 1};
int compressed[10] = {0};
void main(void)
{
  int i;
  i = 0;
  while (i < 10) {
    compressed[i / 2] = encode(test_data[i],test_data[i + 1]);
    i += 2;
  }
  return;
}


