/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeShmidcat */

#ifndef _Included_NativeShmidcat
#define _Included_NativeShmidcat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeShmidcat
 * Method:    shmidcat_init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_unisim_workbench_simulation_services_instruments_gtkwave_model_NativeShmidcat_shmidcat_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeShmidcat
 * Method:    shmidcat_emit_string
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_unisim_workbench_simulation_services_instruments_gtkwave_model_NativeShmidcat_shmidcat_1emit_1string
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeShmidcat
 * Method:    shmidcat_exit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_unisim_workbench_simulation_services_instruments_gtkwave_model_NativeShmidcat_shmidcat_1exit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
